spring.application.name=demo

spring.datasource.url=jdbc:sqlserver://localhost:1433;database=soportec;encrypt=true;trustServerCertificate=true;hostNameInCertificate=*.database.windows.net;loginTimeout=30;

server.address=0.0.0.0
spring.datasource.username=soportec_spring
spring.datasource.password=soportec
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.default_schema=dbo


SECRET_KEY= MiClaveSuperSecretaParaSoportecDebeSerMuySegura123456
jwt.expiration=3600000
